nameOverride: jenkins

master:
  adminUser: "admin"
  adminPassword: "password"

  # resources:
  #   requests:
  #     cpu: 1000m
  #     memory: 1Gi
  #   limits:
  #     cpu: 2000m
  #     memory: 3Gi

  # podAnnotations:
  #   cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

  hostNetworking: true

  javaOpts: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
    hostName: "jenkins.demo.mzdev.be"
    tls:
      - secretName: jenkins-tls
        hosts:
          - "jenkins.demo.mzdev.be"

  installPlugins:
    # https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
    - configuration-as-code:latest

  # https://plugins.jenkins.io/
  additionalPlugins:
    - authorize-project:latest
    - blueocean:latest
    - generic-webhook-trigger:latest
    - keycloak:latest
    - kubernetes-credentials-provider:latest
    - pipeline-github-lib:latest
    - prometheus:latest
    - role-strategy:latest

  overwritePlugins: true

  prometheus:
    enabled: true
    serviceMonitorAdditionalLabels:
      release: prometheus-operator

  # https://plugins.jenkins.io/configuration-as-code/
  JCasC:
    enabled: true
    defaultConfig: true

    configScripts:
      welcome-message: |-
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.

      # https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/keycloak/README.md
      keycloak-json: |-
        unclassified:
          keycloakSecurityRealm:
            keycloakJson: |-
              {
                "realm": "demo",
                "auth-server-url": "https://keycloak.demo.mzdev.be/auth/",
                "ssl-required": "external",
                "resource": "jenkins",
                "credentials": {
                  "secret": "f76f3359-4be2-45dd-aba9-6f5204e62438"
                },
                "confidential-port": 0
              }

      # # https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/jobs/multibranch-github.yaml
      # jobs: |-
      #   jobs:
      #     - script: >
      #         multibranchPipelineJob('sample-node') {
      #           branchSources {
      #             github {
      #               // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
      #               id('100') // IMPORTANT: use a constant and unique identifier
      #               // scanCredentialsId('github')
      #               repoOwner('nalbam')
      #               repository('sample-node')
      #               // apiUri('http://my-github-server/api/v3') // Optional, needed for private github enterprise servers
      #             }
      #           }
      #           orphanedItemStrategy {
      #             discardOldItems {
      #               numToKeep(15)
      #             }
      #           }
      #         }

    # https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/keycloak/README.md
    securityRealm: |-
      keycloak

    # https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/role-strategy-auth/README.md
    authorizationStrategy: |-
      roleBased:
        roles:
          global:
            - name: "admin"
              description: "Administrators"
              permissions:
                - "Overall/Administer"
              assignments:
                - "admin"
                - "jyyu@mz.co.kr"
            - name: "readonly"
              description: "Read-only users"
              permissions:
                - "Overall/Read"
                - "Job/Read"
              assignments:
                - "authenticated"

  jobs:
    sample-node: |-
      <?xml version='1.1' encoding='UTF-8'?>
      <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject plugin="workflow-multibranch@2.21">
        <actions/>
        <description></description>
        <properties>
          <org.jenkinsci.plugins.docker.workflow.declarative.FolderConfig plugin="docker-workflow@1.23">
            <dockerLabel></dockerLabel>
            <registry plugin="docker-commons@1.16"/>
          </org.jenkinsci.plugins.docker.workflow.declarative.FolderConfig>
          <org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty plugin="kubernetes@1.25.2">
            <permittedClouds/>
          </org.csanchez.jenkins.plugins.kubernetes.KubernetesFolderProperty>
        </properties>
        <healthMetrics>
          <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.12">
            <nonRecursive>false</nonRecursive>
          </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
        </healthMetrics>
        <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.12">
          <pruneDeadBranches>true</pruneDeadBranches>
          <daysToKeep>20</daysToKeep>
          <numToKeep>20</numToKeep>
        </orphanedItemStrategy>
        <triggers/>
        <disabled>false</disabled>
        <sources class="jenkins.branch.MultiBranchProject$BranchSourceList" plugin="branch-api@2.5.5">
          <data>
            <jenkins.branch.BranchSource>
              <source class="jenkins.plugins.git.GitSCMSource" plugin="git@4.2.2">
                <id>sample-node</id>
                <remote>https://github.com/nalbam/sample-node</remote>
                <credentialsId></credentialsId>
                <traits>
                  <jenkins.plugins.git.traits.BranchDiscoveryTrait/>
                </traits>
              </source>
              <strategy class="jenkins.branch.DefaultBranchPropertyStrategy">
                <properties class="empty-list"/>
              </strategy>
            </jenkins.branch.BranchSource>
          </data>
        </sources>
        <factory class="org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory">
          <scriptPath>Jenkinsfile</scriptPath>
        </factory>
      </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>

persistence:
  enabled: true
  storageClass: default
  size: 20Gi

rbac:
  create: true
  readSecrets: true

serviceAccount:
  create: true

serviceAccountAgent:
  create: true
